setenv LANG "en_US.ISO8859-1"
setenv MM_CHARSET "ISO-8859-1"

alias h		history 25
alias j		jobs -l
alias la	ls -aF
alias lf	ls -FA
alias ll	ls -lAF

alias heimdall		ssh root@heimdall
alias malekith		ssh root@malekith
alias os-buildnode	ssh root@os-buildnode

# A righteous umask
umask 22

set path = (/sbin /bin /usr/sbin /usr/bin /usr/local/sbin /usr/local/bin $HOME/bin)

setenv	EDITOR	vim
setenv	PAGER	less
setenv	BLOCKSIZE	K

if ($?prompt) then
	# An interactive shell -- set some stuff up
	set prompt = "%N@%m:%~ %# "
	set promptchars = "%#"

	set filec
	set history = 1000
	set savehist = (1000 merge)
	set autolist = ambiguous
	# Use history to aid expansion
	set autoexpand
	set autorehash
	set mail = (/var/mail/$USER)
	if ( $?tcsh ) then
		bindkey "^W" backward-delete-word
		bindkey -k up history-search-backward
		bindkey -k down history-search-forward
	endif

	[ -r ${HOME}/.ssh-agent ] && source ${HOME}/.ssh-agent

	ssh-add -l | grep -q "${HOME}/.ssh/id_rsa" || ssh-add
endif

