---
- name: Setup for developing
  hosts: workstations
  tasks:
        - name: Install packages
          become: yes
          package:
              name: "{{ item }}"
              state: latest
          loop:
                - virtualbox-ose-kmod
                - virtualbox-ose
                - intellij-ultimate
                - vagrant
                - python36
                - python3
                - py36-pipenv
                - qtcreator
                - packer
                - cmake
                - hs-ShellCheck
        - name: Vim Developer Plugins
          block:
              - name: Create vim's plugin folder
                file:
                    path: ~/.vim/ftplugin
                    state: directory
              - name: Install development plugins for vim
                copy:
                    src: "{{ item.src }}"
                    dest: "~/.vim/ftplugin/{{ item.dest }}"
                with_items:
                    - { src: 'vim/ftplugin/c.vim',      dest: 'c.vim' }
                    - { src: 'vim/ftplugin/yaml.vim',   dest: 'yaml.vim' }
        - name: Custom utility programs
          block:
              - name: Create user's bin directory
                file:
                    path: ~/bin
                    state: directory
              - name: Install utilities for the user
                copy:
                  src: "{{ item.src }}"
                  dest: "~/bin/{{ item.dest }}"
                  mode: "a=rx"
                with_items:
                    - { src: 'bin/rsync-auto.sh',   dest: 'rsync-auto' }
...
