---
# http://daemon-notes.com/articles/network/docker
# Run the commands to launch the first docker vm
- name: Setup for using docker
  hosts: workstations
  tasks:
    - name: Install packages
      become: yes
      package:
          name: "{{ item }}"
          state: latest
      loop:
        - docker
        - docker-machine
        - docker-compose
    - name: Create docker directory
      file:
        path: ~/.docker
        state: directory
        owner: "{{ user }}"
    - name: Link docker storage to home directory
      file:
        src: /zroot/docker
        dest: ~/.docker/machine
        owner: "{{ user }}"
        state: link
    - name: Installing admin tool for docker
      block:
        - file:
            path: ~/bin
            state: directory
        - copy:
            src: 'docker/mydocker.sh'
            dest: '~/bin/mydocker'
            mode: 0777
...
