---
- name: Setup for workstations (Email, web-browsing, ...)
  #  hosts: '{{ target }}'
  hosts: workstations
  tasks:
    - name: Install packages
      become: yes
      package: name={{ item.name }} state={{ item.state }}
      with_items:
        - { name: 'xorg',               state: 'present' }
        - { name: 'i3',                 state: 'present' }
        - { name: 'i3status',           state: 'present' }
        - { name: 'i3lock',             state: 'present' }
        - { name: 'dmenu',              state: 'present' }
        - { name: 'vim-console',        state: 'present' }
        - { name: 'firefox',            state: 'present' }
        - { name: 'tmux',               state: 'present' }
        - { name: 'htop',               state: 'present' }
        - { name: 'apache24',           state: 'absent'  }
        - { name: 'cups',               state: 'present' }
        - { name: 'neomutt',            state: 'present' }
        - { name: 'profanity',          state: 'present' }
        - { name: 'pidgin',             state: 'present' }
        - { name: 'rxvt-unicode',       state: 'present' }
        - { name: 'slim',               state: 'present' }
        - { name: 'rsync',              state: 'present' }
        - { name: 'thunderbird',        state: 'absent'  }
        - { name: 'nitrogen',           state: 'present' }
        - { name: 'git',                state: 'present' }
        - { name: 'subversion',         state: 'present' }
        - { name: 'libreoffice',        state: 'present' }
        - { name: 'cups-filters',       state: 'present' }
        - { name: 'gutenprint',         state: 'present' }
        - { name: 'evolution',          state: 'present' }
    - name: Create configuration directories
      file: path={{ item.path }} state=directory
      with_items:
        - { path: '~/.config' }
        - { path: '~/.config/i3' }
        - { path: '~/.config/i3status' }
        - { path: '~/.config/nitrogen' }
        - { path: '~/.config/resources' }
    - name: Configure i3
      block:
          - name: Create folders needed by i3
            file: path={{ item }} state=directory
            loop:
                - ~/.config/i3
                - ~/.config/i3status
                - ~/.i3
                - ~/.config/nitrogen
                - ~/.config/resources
          - name: Install configuration files for i3
            copy: src={{ item.src }} dest={{ item.dest }}
            with_items:
                - { src: 'i3/i3_config',        dest: '~/.config/i3/config'       }
                - { src: 'i3/i3status_config',  dest: '~/.config/i3status/config' }
                - { src: 'i3/i3status.sh',      dest: '~/.i3/i3status.sh'         }
                - { src: 'config/nitrogen.cfg', dest: '~/.config/nitrogen/nitrogen.cfg'    }
                - { src: 'resources/background.png', dest: '~/.config/resources/background.png' }
    - name: Configure vim
      block:
          - name: Create vim autoload folder
            file:
                path: ~/.vim/autoload
                state: directory
          - name: Configure vim
            synchronize:
                src: vim/vimrc
                dest: ~/.vimrc
          - name: Fetch plugin manager
            get_url:
                url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
                dest: ~/.vim/autoload/plug.vim
          - name: Install the needed plugins for vim
            shell: 'vim "+PlugInstall | qa"'
    - name: Configure profanity
      copy:
        src: 'profanity/profrc'
        dest: '~/.config/profanity/profrc'
    - name: Configure mutt, xorg, csh, mailcap
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: 'config/Xdefaults',    dest: '~/.Xdefaults'    }
        - { src: 'config/muttrc',       dest: '~/.muttrc'       }
        - { src: 'config/mailcap',      dest: '~/.mailcap'      }
        - { src: 'config/cshrc',        dest: '~/.cshrc'        }
        - { src: 'config/tmux.conf',    dest: '~/.tmux.conf'    }
    - name: Loading the kmod coretemp on rc
      become: yes
      command: sysrc kld_list+=coretemp
      when: ansible_os_family == "FreeBSD"
    - name: install system builder
      block:
          - name: Create bin folder
            file:
                path: ~/bin
                state: directory
          - name: Install programs
            become: yes
            copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
            with_items:
                - { src: 'bin/system-builder.sh', dest: '/usr/local/sbin/system-builder', mode: '0755' }
    - name: Setup root's crontab
      block:
          - name: Copy crontab
            copy:
                src: crontab
                dest: /tmp/crontab
          - name: Install crontab
            become: yes
            command: crontab -u root /tmp/crontab
...
